// Parametry regulatora ecoMAX (kocioł Pellux 200, ecoMAX 860P2) do panelu „Ustawienia zaawansowane”.
// Numer = indeks w odpowiedzi 0xB1/0xB2 i w ramce zmiany 0x33/0x34. Nazwy, jednostki, krok i
// przesunięcie z biblioteki PyPlumIO (parameters/ecomax.py i mixer.py, ProductType.ECOMAX_P,
// 0.6.8), nazwy z panelu, opisy i oceny z devices/pellet-boiler-pelux200/docs/parametry-kotla.md
// (wygenerowane 2026-10-03; przy zmianie opisu poprawić oba miejsca). Grupy — podział do panelu
// aplikacji. Wartość na ekranie = (surowa − offset) × step.

export type EcomaxParameterGroup =
  | 'boiler'
  | 'water_heater'
  | 'pumps'
  | 'summer'
  | 'weather'
  | 'thermostat'
  | 'power'
  | 'kindling'
  | 'supervision'
  | 'burning_off'
  | 'fuel'
  | 'buffer'
  | 'grate'
  | 'other';

export interface EcomaxParameterDefinition {
  index: number;
  /** nazwa w PyPlumIO */
  name: string;
  /** polska nazwa (gdy brak — pokazywana jest name) */
  label?: string;
  /** co zmienia (z docs/parametry-kotla.md, ze źródłem w instrukcji) */
  description?: string;
  /** ocena zmiany: bezpieczny z aplikacji / ostrożnie / tylko serwis / nie ruszać */
  rating?: string;
  unit?: string;
  step?: number;
  offset?: number;
  /** przełącznik 0/1 (PyPlumIO SwitchDescription) */
  kind?: 'switch';
}

export const ECOMAX_PARAMETER_GROUPS: { key: EcomaxParameterGroup; label: string }[] = [
  { key: 'boiler', label: "Kocioł: temperatury i histerezy" },
  { key: 'water_heater', label: "CWU" },
  { key: 'pumps', label: "Pompy i obieg CO" },
  { key: 'summer', label: "Tryb LATO" },
  { key: 'weather', label: "Sterowanie pogodowe" },
  { key: 'thermostat', label: "Termostat" },
  { key: 'power', label: "Moc, nadmuch i podajnik" },
  { key: 'kindling', label: "Rozpalanie" },
  { key: 'supervision', label: "Stabilizacja i nadzór" },
  { key: 'burning_off', label: "Wygaszanie i czyszczenie" },
  { key: 'fuel', label: "Paliwo" },
  { key: 'buffer', label: "Bufor i cyrkulacja" },
  { key: 'grate', label: "Praca na ruszcie" },
  { key: 'other', label: "Inne" },
];

export const ECOMAX_PARAMETERS: (EcomaxParameterDefinition & { group: EcomaxParameterGroup })[] = [
  { index: 0, name: 'airflow_power_100', label: "Moc nadmuchu 100%", description: "Obroty wentylatora przy mocy maksymalnej. Wpływa na spalanie (Pellux str. 37 i 41, instr. 860P str. 39).", rating: "Tylko serwis.", unit: "%", group: 'power' },
  { index: 1, name: 'airflow_power_50', label: "Moc nadmuchu 50%", description: "Obroty wentylatora przy mocy pośredniej (Pellux str. 41).", rating: "Tylko serwis.", unit: "%", group: 'power' },
  { index: 2, name: 'airflow_power_30', label: "Moc nadmuchu 30%", description: "Obroty wentylatora przy mocy minimalnej (Pellux str. 41).", rating: "Tylko serwis.", unit: "%", group: 'power' },
  { index: 3, name: 'boiler_power_100', label: "Maksymalna moc kotła", description: "Moc kotła przypisana do poziomu 100 %. Na zrzucie w instrukcji 20 kW (Pellux str. 37 i 41).", rating: "Nie dotyczy.", unit: "kW", group: 'power' },
  { index: 4, name: 'boiler_power_50', label: "Pośrednia moc kotła", description: "Moc kotła przypisana do poziomu 50 %. Na zrzucie 10 kW (Pellux str. 41).", rating: "Nie dotyczy.", unit: "kW", group: 'power' },
  { index: 5, name: 'boiler_power_30', label: "Minimalna moc kotła", description: "Moc kotła przypisana do poziomu 30 %. Na zrzucie 6 kW (Pellux str. 41).", rating: "Nie dotyczy.", unit: "kW", group: 'power' },
  { index: 6, name: 'max_fan_boiler_power', description: "Maksymalna moc wentylatora, prawdopodobnie wyciągowego (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "%", group: 'power' },
  { index: 7, name: 'min_fan_boiler_power', description: "Minimalna moc wentylatora, prawdopodobnie wyciągowego (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "%", group: 'power' },
  { index: 8, name: 'fuel_feeding_work_100', description: "Czas pracy podajnika w cyklu przy mocy 100 % (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "s", group: 'power' },
  { index: 9, name: 'fuel_feeding_work_50', description: "Czas pracy podajnika przy mocy 50 % (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "s", group: 'power' },
  { index: 10, name: 'fuel_feeding_work_30', description: "Czas pracy podajnika przy mocy 30 % (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "s", group: 'power' },
  { index: 11, name: 'fuel_feeding_pause_100', description: "Przerwa podajnika w cyklu przy mocy 100 % (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "s", group: 'power' },
  { index: 12, name: 'fuel_feeding_pause_50', description: "Przerwa podajnika przy mocy 50 % (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "s", group: 'power' },
  { index: 13, name: 'fuel_feeding_pause_30', description: "Przerwa podajnika przy mocy 30 % (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "s", group: 'power' },
  { index: 14, name: 'cycle_duration', label: "Cykl pracy podajnika (Czas cyklu PRACA)", description: "Długość cyklu podajnika w trybie PRACA: czas podawania + czas postoju. Czas podawania regulator liczy z wymaganej mocy, wydajności podajnika i kaloryczności paliwa. Fabrycznie 20 s (Pellux str. 41, instr. 850P2 str. 10 i 35).", rating: "Tylko serwis.", unit: "s", group: 'power' },
  { index: 15, name: 'h2_hysteresis', label: "50% Histereza H2", description: "Próg przejścia z mocy 100 % na 50 % przy zbliżaniu się do zadanej. Fabrycznie 5 °C. Tylko w trybie Standardowym (Pellux str. 41, instr. 850P2 str. 11).", rating: "Ostrożnie. U nas bez znaczenia (Fuzzy Logic).", unit: "°C", group: 'boiler' },
  { index: 16, name: 'h1_hysteresis', label: "30% Histereza H1", description: "Próg przejścia z mocy 50 % na 30 %. Fabrycznie 3 °C. Tylko w trybie Standardowym (Pellux str. 41, instr. 850P2 str. 11).", rating: "Ostrożnie. U nas bez znaczenia (Fuzzy Logic).", unit: "°C", group: 'boiler' },
  { index: 17, name: 'heating_hysteresis', label: "Histereza kotła", description: "Kocioł rozpala, gdy temperatura spadnie poniżej zadanej minus histereza (instr. 860P str. 12 i 41, Pellux str. 41). U nas start przy 67 − 10 = 57 °C. Fabrycznie 10 °C (Pellux str. 41).", rating: "Bezpieczny z aplikacji. Mała histereza daje częste rozpalanie.", unit: "°C", group: 'boiler' },
  { index: 18, name: 'fuzzy_logic', label: "Tryb regulacji", description: "Standardowy (trzy poziomy mocy) albo Fuzzy Logic (płynna moc, PID). Fabrycznie Fuzzy Logic. Przy samym grzaniu CWU (LATO bez bufora) instrukcje zalecają Standardowy. W Fuzzy Logic kocioł przechodzi do NADZORU dopiero po przekroczeniu zadanej o 5 °C (Pellux str. 41, instr. 860P str. 11, 850P2 str. 11). PyPlumIO opisuje go jako przełącznik, regulator podaje 0–2; 2 to prawdopodobnie „Lambda Fuzzy Logic” (850P2 str. 8, niepotwierdzone).", rating: "Ostrożnie. Zmienia sposób spalania. Lepiej zostawić Fuzzy Logic.", kind: 'switch', group: 'power' },
  { index: 19, name: 'min_fuzzy_logic_power', label: "Min moc kotła FL", description: "Dolna granica mocy kotła w trybie Fuzzy Logic (instr. 850P2 str. 8 i 11).", rating: "Nie dotyczy.", unit: "%", group: 'power' },
  { index: 20, name: 'max_fuzzy_logic_power', label: "Max moc kotła FL", description: "Górna granica mocy kotła w trybie Fuzzy Logic (instr. 850P2 str. 8 i 11).", rating: "Nie dotyczy.", unit: "%", group: 'power' },
  { index: 21, name: 'min_boiler_power', description: "Minimalna moc kotła (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "kW", group: 'power' },
  { index: 22, name: 'max_boiler_power', label: "Ograniczenie max. mocy kotła", description: "Maksymalna moc kotła (opis z nazwy, niepotwierdzony). W menu Pellux jest „Ograniczenie max. mocy kotła” 20 kW (str. 33).", rating: "Nie dotyczy.", unit: "kW", group: 'power' },
  { index: 23, name: 'min_fan_power', label: "Minimalna moc nadmuchu", description: "Najmniejsza moc wentylatora, jaką może wybrać użytkownik. Ogranicza tylko zakres w menu, nie algorytm. Wentylator ma się obracać wolno, bez buczenia (Pellux str. 43, instr. 850P2 str. 36).", rating: "Tylko serwis.", unit: "%", group: 'power' },
  { index: 24, name: 'max_fan_power', label: "Maksymalna moc nadmuchu", description: "Największa moc wentylatora, jaką może wybrać użytkownik. Ogranicza tylko zakres w menu (Pellux str. 43).", rating: "Tylko serwis.", unit: "%", group: 'power' },
  { index: 25, name: 'reduction_airflow_temp', label: "Temperatura spalin – redukcja nadmuchu", description: "Powyżej tej temperatury spalin regulator zmniejsza obroty wentylatora do minimum (instr. 860P str. 41).", rating: "Nie dotyczy.", unit: "°C", group: 'power' },
  { index: 26, name: 'fan_power_gain', label: "Wzmocnienie reg. PI wentylatora", description: "Wzmocnienie regulacji mocy wentylatora (opis z nazwy, niepotwierdzony). W menu Pellux jest „Wzmocnienie reg. PI wentylatora” (str. 38), bez opisu.", rating: "Nie dotyczy.", unit: "%", group: 'power' },
  { index: 27, name: 'fuzzy_logic_fuel_flow_correction', description: "Korekta ilości paliwa w trybie Fuzzy Logic (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "%", group: 'power' },
  { index: 28, name: 'fuel_flow_correction', label: "Korekta paliwa", description: "Korekta ilości podawanego paliwa (opis z nazwy, niepotwierdzony). W menu Pellux jest „Korekta paliwa” 0 % (str. 33), bez opisu.", rating: "Nie dotyczy.", unit: "%", group: 'power' },
  { index: 29, name: 'airflow_correction_100', description: "Korekta nadmuchu przy mocy 100 % (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "%", group: 'power' },
  { index: 30, name: 'feeder_correction_100', description: "Korekta podajnika przy mocy 100 % (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "%", group: 'power' },
  { index: 31, name: 'airflow_correction_50', description: "Korekta nadmuchu przy mocy 50 % (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "%", group: 'power' },
  { index: 32, name: 'feeder_correction_50', description: "Korekta podajnika przy mocy 50 % (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "%", group: 'power' },
  { index: 33, name: 'airflow_correction_30', description: "Korekta nadmuchu przy mocy 30 % (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "%", group: 'power' },
  { index: 34, name: 'feeder_correction_30', description: "Korekta podajnika przy mocy 30 % (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "%", group: 'power' },
  { index: 35, name: 'grate_airflow_power', label: "Moc nadmuchu – ruszt", description: "Nadmuch przy pracy na ruszcie (instr. 850P2 str. 8 i 12).", rating: "Nie dotyczy.", unit: "%", group: 'grate' },
  { index: 36, name: 'grate_heating_hysteresis', label: "Histereza kotła (ruszt)", description: "Histereza kotła osobno dla rusztu (instr. 850P2 str. 12).", rating: "Nie dotyczy.", unit: "°C", group: 'grate' },
  { index: 37, name: 'grate_fan_work', label: "Praca przedmuchu – nadzór", description: "Czas przedmuchu w NADZORZE na ruszcie. Za długi przegrzewa wodę (instr. 860P str. 41).", rating: "Nie dotyczy.", unit: "s", group: 'grate' },
  { index: 38, name: 'grate_fan_pause', label: "Przerwa przedmuchu – nadzór", description: "Przerwa między przedmuchami w NADZORZE na ruszcie (instr. 860P str. 41).", rating: "Nie dotyczy.", unit: "min", group: 'grate' },
  { index: 39, name: 'grate_heating_temp', label: "Temp. zadana kotła (ruszt)", description: "Zadana kotła osobno dla rusztu (instr. 850P2 str. 12).", rating: "Nie dotyczy.", unit: "°C", group: 'grate' },
  { index: 40, name: 'grate_fuel_detection_time', label: "Czas detekcji braku paliwa (ruszt)", description: "Czas liczony po spadku temperatury spalin poniżej progu; 0 = wykrywanie wyłączone (instr. 860P str. 40–41).", rating: "Nie dotyczy.", unit: "min", group: 'grate' },
  { index: 41, name: 'kindling_airflow_power', label: "Moc nadmuchu rozpalania", description: "Nadmuch przy rozpalaniu. Za duży wydłuża rozpalanie albo daje nieudaną próbę (Pellux str. 42, instr. 860P str. 39).", rating: "Tylko serwis.", unit: "%", group: 'kindling' },
  { index: 42, name: 'kindling_low_airflow_power', description: "Niski nadmuch w części rozpalania (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "%", group: 'kindling' },
  { index: 43, name: 'kindling_airflow_delay', description: "Opóźnienie albo wydłużenie nadmuchu przy rozpalaniu (opis z nazwy, niepotwierdzony). W 860P jest „Wydłużenie nadmuchu” w rozpalaniu (str. 39).", rating: "Nie dotyczy.", unit: "s", group: 'kindling' },
  { index: 44, name: 'kindling_test_time', label: "Czas testu zapłonu", description: "Czas sprawdzania, czy palenisko już się pali. Pracuje tylko wentylator. Przy jasnym płomieniu kocioł pomija rozpalanie i przechodzi do PRACY (instr. 860P str. 39, Pellux str. 42).", rating: "Tylko serwis.", unit: "s", group: 'kindling' },
  { index: 45, name: 'kindling_feeder_work', label: "Czas podawania (rozpalanie)", description: "Czas podawania dawki paliwa przy pierwszej próbie rozpalenia (instr. 860P str. 39).", rating: "Nie dotyczy.", group: 'kindling' },
  { index: 46, name: 'kindling_feeder_dose', label: "Dawka paliwa", description: "Masa paliwa przy pierwszej próbie rozpalenia. W kolejnych próbach mniej. Fabrycznie 170 g (Pellux str. 8 i 42).", rating: "Nie dotyczy.", unit: "g", group: 'kindling' },
  { index: 47, name: 'kindling_time', label: "Czas rozpalania", description: "Czas jednej próby rozpalenia. Potem kolejna próba, najwyżej 3 (Pellux str. 42).", rating: "Tylko serwis.", unit: "min", group: 'kindling' },
  { index: 48, name: 'warming_up_time', label: "Czas rozgrzewania", description: "Czas rozgrzewania zapalarki przed włączeniem wentylatora. Nie może być za długi, żeby nie uszkodzić grzałki (Pellux str. 42, instr. 860P str. 39). Wartość 30 min wygląda na dużą; jednostka niepewna.", rating: "Tylko serwis.", unit: "min", group: 'kindling' },
  { index: 49, name: 'kindling_finish_exhaust_temp', description: "Temperatura spalin kończąca rozpalanie (opis z nazwy, niepotwierdzony). Nasz kocioł wykrywa płomień czujnikiem optycznym.", rating: "Nie dotyczy.", unit: "°C", group: 'kindling' },
  { index: 50, name: 'kindling_finish_threshold_temp', label: "Płomień końca rozpalenia", description: "PyPlumIO: próg temperatury (°C). Zakres 1–100 bardziej pasuje do „Płomień końca rozpalenia”: próg jasności płomienia w % światła, przy którym regulator uznaje palenisko za rozpalone; służy też do wykrywania braku paliwa i końca wygaszania (Pellux str. 42). Przypisanie niepotwierdzone.", rating: "Nie ruszać. Znaczenie niepewne.", unit: "°C", group: 'kindling' },
  { index: 51, name: 'kindling_fumes_delta_temp', description: "Przyrost temperatury spalin przy rozpalaniu (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "°C", group: 'kindling' },
  { index: 52, name: 'kindling_delta_temp', description: "Przyrost temperatury przy rozpalaniu (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "°C", group: 'kindling' },
  { index: 53, name: 'kindling_min_power_time', label: "Czas pracy z mocą minimalną (albo Czas rozżarzania?)", description: "Czas pracy palnika z mocą minimalną po rozpaleniu (instr. 850P2 str. 35). W menu Pellux w tym miejscu jest „Czas rozżarzania”: czas rozżarzania po wykryciu płomienia (Pellux str. 42). Które z nich, niepotwierdzone.", rating: "Tylko serwis.", unit: "min", group: 'kindling' },
  { index: 54, name: 'stabilization_time', label: "Czas stabilizacji", description: "Czas pracy w trybie STABILIZACJA po rozpaleniu (instr. 860P str. 39).", rating: "Nie dotyczy.", unit: "min", group: 'supervision' },
  { index: 55, name: 'stabilization_airflow_power', label: "Moc nadmuchu – stabilizacja (u Pellux może to być „Moc nadmuchu ROZŻARZANIE” albo „Nadmuch po rozpaleniu”)", description: "Nadmuch w trybie STABILIZACJA (instr. 860P str. 39). Odpowiednik w menu Pellux niepotwierdzony (Pellux str. 37 i 42).", rating: "Tylko serwis.", unit: "%", group: 'supervision' },
  { index: 56, name: 'supervision_time', label: "Czas nadzoru", description: "Najdłuższy czas w NADZORZE, potem wygaszanie. 0 = kocioł pomija NADZÓR i od razu wygasza. 60 = NADZÓR bez limitu, aż temperatura spadnie i kocioł wróci do PRACY (Pellux str. 43). U nas 0: po przekroczeniu zadanej o 5 °C kocioł wygasza i czeka w POSTOJU na spadek do 57 °C.", rating: "Tylko serwis.", group: 'supervision' },
  { index: 57, name: 'supervision_feeder_work', label: "Czas podawania (nadzór)", description: "Czas podawania paliwa w NADZORZE. Ma być mały, tylko do podtrzymania płomienia. Za duży przegrzewa kocioł (instr. 860P str. 40).", rating: "Nie dotyczy.", unit: "s", group: 'supervision' },
  { index: 58, name: 'supervision_feeder_dose', description: "Dawka paliwa w NADZORZE (opis z nazwy, niepotwierdzony). W menu Pellux jest „Moc kotła w trybie NADZÓR” (str. 43).", rating: "Nie dotyczy.", unit: "g", group: 'supervision' },
  { index: 59, name: 'supervision_feeder_pause', label: "Czas przerwy (nadzór)", description: "Przerwa w podawaniu paliwa w NADZORZE (instr. 860P str. 40).", rating: "Nie dotyczy.", unit: "min", group: 'supervision' },
  { index: 60, name: 'supervision_cycle_duration', label: "Czas cyklu NADZÓR", description: "Cykl podajnika w NADZORZE: czas podawania + czas postoju (Pellux str. 43).", rating: "Tylko serwis. U nas nieużywany (nr 56 = 0).", unit: "s", group: 'supervision' },
  { index: 61, name: 'supervision_airflow_power', label: "Moc nadmuchu NADZÓR", description: "Nadmuch w NADZORZE. Za duży grozi przegrzaniem albo cofnięciem płomienia do podajnika, za mały przesypaniem paliwa (Pellux str. 43, instr. 860P str. 40).", rating: "Tylko serwis. U nas nieużywany (nr 56 = 0).", unit: "%", group: 'supervision' },
  { index: 62, name: 'supervision_fan_pause', description: "Przerwa wentylatora w NADZORZE (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "min", group: 'supervision' },
  { index: 63, name: 'supervision_fan_work', description: "Czas pracy wentylatora w NADZORZE (opis z nazwy, niepotwierdzony). W 860P jest „Wydłużenie nadmuchu”: wentylator pracuje po podaniu dawki, za długo przegrzewa kocioł (str. 40).", rating: "Nie dotyczy.", unit: "s", group: 'supervision' },
  { index: 64, name: 'increase_fan_support_mode', description: "Tryb zwiększenia nadmuchu (opis z nazwy, niepotwierdzony). W 860P jest „Zwiększenie mocy nadmuchu” po czyszczeniu palnika (str. 40).", rating: "Nie dotyczy.", group: 'power' },
  { index: 65, name: 'burning_off_max_time', label: "Maksymalny czas wygaszania", description: "Po tym czasie kocioł przechodzi do POSTOJU, nawet gdy czujnik nadal widzi płomień (Pellux str. 42, instr. 860P str. 39).", rating: "Tylko serwis.", unit: "min", group: 'burning_off' },
  { index: 66, name: 'burning_off_min_time', label: "Minimalny czas wygaszania", description: "Wygaszanie trwa co najmniej tyle, nawet gdy płomienia już nie widać (Pellux str. 42).", rating: "Tylko serwis.", unit: "min", group: 'burning_off' },
  { index: 67, name: 'burning_off_time', label: "Czas wygaszania", description: "Czas wygaszania (opis z nazwy, niepotwierdzony). W 860P „Czas wygaszania” to czas minimalny (str. 39), co dubluje nr 66.", rating: "Nie dotyczy.", group: 'burning_off' },
  { index: 68, name: 'burning_off_airflow_power', label: "Nadmuch wygaszania", description: "Obroty wentylatora przy wygaszaniu (Pellux str. 42).", rating: "Tylko serwis.", unit: "%", group: 'burning_off' },
  { index: 69, name: 'burning_off_fan_work', label: "Czas przedmuchu", description: "Czas jednego przedmuchu przy dopalaniu paliwa w wygaszaniu (instr. 860P str. 39, 850P2 str. 35).", rating: "Tylko serwis.", group: 'burning_off' },
  { index: 70, name: 'burning_off_fan_pause', label: "Przerwa przedmuchu", description: "Przerwa między przedmuchami w wygaszaniu (instr. 860P str. 39).", rating: "Tylko serwis.", group: 'burning_off' },
  { index: 71, name: 'start_burning_off', label: "Start przedmuchu", description: "Jasność płomienia, przy której zaczynają się przedmuchy w wygaszaniu (instr. 860P str. 39, 850P2 str. 36).", rating: "Tylko serwis.", unit: "%", group: 'burning_off' },
  { index: 72, name: 'stop_burning_off', label: "Stop przedmuchu", description: "Jasność płomienia, przy której przedmuchy się kończą (instr. 860P str. 39, 850P2 str. 36).", rating: "Tylko serwis.", unit: "%", group: 'burning_off' },
  { index: 73, name: 'cleaning_begin_time', label: "Czas czyszczenia rozpalanie", description: "Czas pracy wentylatora przy czyszczeniu paleniska podczas rozpalania (instr. 850P2 str. 36). Przypisanie z nazwy PyPlumIO, niepotwierdzone.", rating: "Tylko serwis.", group: 'burning_off' },
  { index: 74, name: 'burning_off_cleaning_time', label: "Czas czyszczenia wygaszanie", description: "Czas pracy wentylatora przy czyszczeniu paleniska podczas wygaszania (instr. 850P2 str. 36).", rating: "Nie dotyczy.", group: 'burning_off' },
  { index: 75, name: 'cleaning_airflow_power', label: "Nadmuch czyszczenia", description: "PyPlumIO: nadmuch przy czyszczeniu paleniska (Pellux str. 42). Zakres 0–1 nie pasuje do mocy; to raczej przełącznik, np. „Czyszczenie w ciszy” (Pellux str. 38 i 42). Znaczenie niepotwierdzone.", rating: "Nie ruszać. Znaczenie niepewne.", unit: "%", group: 'burning_off' },
  { index: 76, name: 'warming_up_pause_time', label: "Czyszczenie palnika", description: "PyPlumIO: przerwa przy rozgrzewaniu (opis z nazwy, niepotwierdzony). Zakres 1–24 pasuje do „Czyszczenie palnika”: maksymalny czas pracy palnika bez czyszczenia, 1–24 h, na zrzucie 6 h; po nim kocioł wygasza, czyści i rozpala ponownie (Pellux str. 34). Hipoteza: sprawdzić na panelu, czy Ustawienia kotła → Czyszczenie palnika pokazuje 4 h.", rating: "Nie ruszać, dopóki znaczenie jest niepewne.", group: 'kindling' },
  { index: 77, name: 'warming_up_cycle_time', description: "Czas cyklu przy rozgrzewaniu (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", group: 'kindling' },
  { index: 78, name: 'remind_time', description: "Czas przypomnienia, np. o czyszczeniu (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", group: 'other' },
  { index: 79, name: 'lambda_control', label: "Praca z sondą Lambda", description: "Włączone: regulator dobiera ilość powietrza do zadanej zawartości tlenu w spalinach (instr. 860P str. 40 i 47, Pellux str. 43).", rating: "Nie dotyczy.", kind: 'switch', group: 'power' },
  { index: 80, name: 'lambda_correction_range', label: "Zakres korekcji nadmuchu", description: "Dopuszczalny zakres zmiany nadmuchu przy pracy z sondą (instr. 860P str. 40).", rating: "Nie dotyczy.", group: 'power' },
  { index: 81, name: 'oxygen_100', label: "100% Tlen", description: "Zadana zawartość tlenu przy mocy 100 % (Pellux str. 37, instr. 850P2 str. 41).", rating: "Nie dotyczy.", group: 'power' },
  { index: 82, name: 'oxygen_50', label: "50% Tlen", description: "Zadana zawartość tlenu przy mocy 50 % (Pellux str. 37, instr. 850P2 str. 41).", rating: "Nie dotyczy.", group: 'power' },
  { index: 83, name: 'oxygen_30', label: "30% Tlen", description: "Zadana zawartość tlenu przy mocy 30 % (Pellux str. 37, instr. 850P2 str. 41).", rating: "Nie dotyczy.", group: 'power' },
  { index: 84, name: 'fuzzy_logic_oxygen_correction', description: "Korekta tlenu w trybie Fuzzy Logic (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", group: 'power' },
  { index: 85, name: 'max_fuel_flow', label: "Wydajność podajnika", description: "Ile paliwa podaje podajnik na godzinę. Regulator liczy z niej czas podawania (instr. 850P2 str. 10) i poziom paliwa (Pellux str. 17). Wynik testu wydajności podajnika. Na zrzucie w instrukcji 11,2 kg/h (Pellux str. 33).", rating: "Tylko serwis. Zła wartość zmienia ilość podawanego paliwa.", unit: "kg/h", step: 0.2, group: 'fuel' },
  { index: 86, name: 'feeder_calibration', label: "Test wydajności podajnika", description: "Kalibracja podajnika (opis z nazwy, niepotwierdzony). W menu Pellux jest „Test wydajności podajnika” (str. 33).", rating: "Nie dotyczy.", group: 'power' },
  { index: 87, name: 'fuel_tank_capacity', label: "Pojemność zbiornika", description: "Pojemność zasobnika do liczenia poziomu paliwa. Używana, dopóki nie zrobiono kalibracji poziomu paliwa (Pellux str. 44, instr. 850P2 str. 35). Nie wpływa na spalanie.", rating: "Bezpieczny z aplikacji, ale wpływa tylko na wskaźnik poziomu paliwa.", unit: "kg", step: 50.0, group: 'fuel' },
  { index: 88, name: 'fuel_calorific_value', label: "Kaloryczność paliwa", description: "Kaloryczność pelletu. Regulator liczy z niej czas podawania (instr. 850P2 str. 10 i 35). Na zrzucie w instrukcji 4,9 kWh/kg (Pellux str. 33).", rating: "Tylko serwis. Zmienia ilość podawanego paliwa.", unit: "kWh/kg", step: 0.1, group: 'fuel' },
  { index: 89, name: 'fuel_detection_time', label: "Czas detekcji braku paliwa", description: "Czas liczony od spadku jasności płomienia poniżej progu. Potem kocioł próbuje rozpalić, po 3 nieudanych próbach alarm (Pellux str. 43).", rating: "Tylko serwis.", unit: "min", group: 'fuel' },
  { index: 90, name: 'fuel_detection_exhaust_temp', label: "Temp. spalin przy braku paliwa", description: "Gdy spaliny są chłodniejsze dłużej niż czas detekcji, regulator uznaje brak paliwa (instr. 860P str. 41).", rating: "Nie dotyczy.", unit: "°C", group: 'fuel' },
  { index: 91, name: 'schedule_feeder_2', description: "Harmonogram podajnika 2 (bunkra) (opis z nazwy, niepotwierdzony). Podajnik bunkra wymaga modułu B (instr. 860P str. 47).", rating: "Nie dotyczy.", kind: 'switch', group: 'power' },
  { index: 92, name: 'feed2_h1', description: "Godzina 1 pracy podajnika 2 (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", group: 'power' },
  { index: 93, name: 'feed2_h2', description: "Godzina 2 pracy podajnika 2 (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", group: 'power' },
  { index: 94, name: 'feed2_h3', description: "Godzina 3 pracy podajnika 2 (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", group: 'power' },
  { index: 95, name: 'feed2_h4', description: "Godzina 4 pracy podajnika 2 (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", group: 'power' },
  { index: 96, name: 'feed2_work', label: "Czas pracy podajnika 2", description: "Czas pracy podajnika dodatkowego, który uzupełnia zasobnik z bunkra. 0 = podajnik wyłączony (instr. 860P str. 47).", rating: "Nie dotyczy.", group: 'power' },
  { index: 97, name: 'feed2_pause', description: "Przerwa podajnika 2 (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", group: 'power' },
  { index: 98, name: 'heating_target_temp', label: "Temperatura zadana kotła", description: "Temperatura wody w kotle, do której kocioł grzeje. Regulator sam ją podnosi na czas ładowania CWU i mieszaczy. Przy włączonym sterowaniu pogodowym regulator pomija tę nastawę (instr. 860P str. 10).", rating: "Bezpieczny z aplikacji. Dolna granica zależy od nr 99.", unit: "°C", group: 'boiler' },
  { index: 99, name: 'min_heating_target_temp', label: "Minimalna temperatura kotła", description: "Najniższa zadana, jaką może ustawić użytkownik i jaką regulator może ustawić sam (obniżenia nocne, sterowanie pogodowe, termostat) (instr. 860P str. 41, Pellux str. 44). Dziś blokuje zadaną poniżej 65 °C.", rating: "Ostrożnie. Menu serwisowe. Niska wartość pozwala na zimny kocioł i roszenie, gdy kocioł się pali. Potrzebna do planu z pompą ciepła (kociol-ustawienia.md, punkt 3).", unit: "°C", group: 'boiler' },
  { index: 100, name: 'max_heating_target_temp', label: "Maksymalna temperatura kotła", description: "Najwyższa zadana, jaką może ustawić użytkownik i regulator (instr. 860P str. 41, Pellux str. 44).", rating: "Nie ruszać. Nie ma potrzeby zmiany. Wyższa wartość zbliża kocioł do progu alarmu.", unit: "°C", group: 'boiler' },
  { index: 101, name: 'heating_pump_enable_temp', label: "Temperatura załączenia pompy CO", description: "Pompa CO włącza się dopiero powyżej tej temperatury kotła. Chroni kocioł przed roszeniem od zimnej wody powrotnej. Samo wyłączanie pompy nie wystarcza jako ochrona przed korozją (instr. 860P str. 42, Pellux str. 45).", rating: "Ostrożnie. Menu serwisowe. Niska wartość przy palącym się kotle sprzyja roszeniu. W planie z pompą ciepła ok. 40 °C.", unit: "°C", group: 'pumps' },
  { index: 102, name: 'pause_heating_for_water_heater', label: "Postój pompy CO podczas ładowania CWU", description: "Przy priorytecie CWU pompa CO stoi. Po tym czasie włącza się na stałe 30 s, żeby nie wychłodzić instalacji (instr. 860P str. 42).", rating: "Bezpieczny z aplikacji. Działa tylko przy priorytecie CWU (nr 122 = Priorytet).", unit: "min", group: 'pumps' },
  { index: 103, name: 'thermostat_pause', label: "Czas postoju pompy CO od termostatu", description: "Ile pompa CO stoi po rozwarciu styku termostatu. Działa przy termostacie włączonym i nr 113 = TAK (instr. 860P str. 42).", rating: "Nie dotyczy.", group: 'thermostat' },
  { index: 104, name: 'thermostat_work', label: "Czas pracy pompy CO od termostatu", description: "Ile pompa CO pracuje między postojami od termostatu (instr. 860P str. 42).", rating: "Nie dotyczy.", group: 'thermostat' },
  { index: 105, name: 'increase_heating_temp_for_water_heater', label: "Podwyższenie temp. kotła od CWU i mieszacza", description: "O ile regulator podnosi zadaną kotła, żeby załadować CWU, bufor i mieszacz. Podnosi tylko wtedy, gdy zadana kotła jest za niska (instr. 860P str. 42, Pellux str. 45).", rating: "Bezpieczny z aplikacji.", unit: "°C", group: 'boiler' },
  { index: 106, name: 'weather_control', label: "Sterowanie pogodowe kotła", description: "Zadana kotła liczona z temperatury zewnętrznej według krzywej grzewczej. Ręczna zadana (nr 98) jest wtedy pomijana (instr. 860P str. 10 i 14).", rating: "Ostrożnie. Po włączeniu aplikacja nie ustawi już zadanej wprost.", kind: 'switch', group: 'weather' },
  { index: 107, name: 'heating_curve', label: "Krzywa grzewcza kotła", description: "Nachylenie krzywej. Wytyczne: podłoga 0,2–0,6, grzejniki 1,0–1,6, kocioł 1,8–4. Dobór doświadczalny, w odstępach kilku dni (instr. 860P str. 14, 850P2 str. 15).", rating: "Bezpieczny z aplikacji. Działa tylko przy nr 106 = wł.", step: 0.1, group: 'weather' },
  { index: 108, name: 'heating_curve_shift', label: "Przesunięcie równoległe krzywej", description: "Przesuwa krzywą w górę lub w dół. Temperatura pokojowa = 20 °C + przesunięcie (instr. 860P str. 13–14, Pellux str. 13).", rating: "Bezpieczny z aplikacji. Działa tylko przy nr 106 = wł.", unit: "°C", offset: 20, group: 'weather' },
  { index: 109, name: 'weather_factor', label: "Współczynnik temperatury pokojowej", description: "Korekta zadanej od panelu pokojowego: (zadana pokojowa − zmierzona) × współczynnik / 10. 0 = bez korekty. Za duży daje wahania temperatury w pokoju (instr. 860P str. 13–14, Pellux str. 14).", rating: "Bezpieczny z aplikacji. Działa przy sterowaniu pogodowym i panelu pokojowym.", group: 'weather' },
  { index: 110, name: 'thermostat_operation', description: "Sposób działania termostatu (opis z nazwy, niepotwierdzony). W instr. 850P2 jest „Funkcja termostatu”: wyłącz palnik / wyłącz pompę / wyłącz wszystko (str. 37), ale przypisanie do tego numeru jest niepewne.", rating: "Nie dotyczy.", group: 'thermostat' },
  { index: 111, name: 'thermostat_mode', label: "Wybór termostatu", description: "Wyłączony (termostat nie wpływa na kocioł), Uniwersalny (styk zwierno-rozwierny), ecoSTER T1–T3 (sygnał z panelu pokojowego) (instr. 860P str. 41, Pellux str. 43). PyPlumIO opisuje go jako przełącznik, ale regulator podaje zakres 0–2.", rating: "Ostrożnie. Podstawa wariantu automatycznego w planie z pompą ciepła.", kind: 'switch', group: 'thermostat' },
  { index: 112, name: 'thermostat_decrease_target_temp', label: "Termostat pokojowy kotła", description: "O ile spada zadana kotła, gdy styk termostatu jest rozwarty (pokój nagrzany). Fabrycznie 0 °C (Pellux str. 41).", rating: "Bezpieczny z aplikacji. Obniżenie nie zejdzie poniżej nr 99.", unit: "°C", group: 'thermostat' },
  { index: 113, name: 'disable_pump_on_thermostat', label: "Wyłączenie pompy od termostatu", description: "TAK: po rozwarciu styku termostatu zamyka mieszacz i wyłącza pompę (instr. 860P str. 41). Pompa CO stoi wtedy na „Czas postoju” i rusza na „Czas pracy” (nr 103/104) (instr. 860P str. 42).", rating: "Ostrożnie. Pokój może się wychłodzić.", kind: 'switch', group: 'thermostat' },
  { index: 114, name: 'boiler_alert_temp', label: "Temperatura schładzania kotła", description: "PyPlumIO: temperatura alarmowa kotła. Zakres 85–95 pasuje do „Temperatury schładzania kotła”: powyżej niej regulator włącza pompę CWU i otwiera mieszacze, żeby schłodzić kocioł (instr. 860P str. 41, Pellux str. 44). Alarm przegrzania jest przy stałych 95 °C. Przypisanie niepotwierdzone. Kopia ustawień opisuje go jako „Temperatura alarmowa kotła (STB)”, ale STB to osobny termostat mechaniczny.", rating: "Nie ruszać. Bezpieczeństwo.", unit: "°C", group: 'boiler' },
  { index: 115, name: 'max_feeder_temp', label: "Maksymalna temperatura podajnika", description: "Powyżej tej temperatury podajnika alarm, wypchnięcie żaru z rury podajnika i wygaszanie. Ochrona przed cofnięciem płomienia (instr. 860P str. 40 i 45).", rating: "Nie dotyczy.", unit: "°C", group: 'power' },
  { index: 116, name: 'external_boiler_temp', label: "Kocioł rezerwowy (temperatura załączenia)", description: "Temperatura kotła pelletowego, poniżej której regulator włącza kocioł rezerwowy (np. gazowy). 0 = bez kotła rezerwowego (instr. 860P str. 41, Pellux str. 47). Przypisanie z nazwy PyPlumIO („kocioł zewnętrzny”) i zakresu, niepotwierdzone.", rating: "Nie ruszać. Do sterowania drugim źródłem przez wyjście H; bez okablowania nic nie da.", unit: "°C", group: 'boiler' },
  { index: 117, name: 'alert_notify', label: "Sygnalizacja alarmów", description: "Wybór alarmów, przy których włącza się wyjście H (Pellux str. 44). Przypisanie z nazwy, niepotwierdzone; PyPlumIO podaje °C, co do tego nie pasuje.", rating: "Nie dotyczy.", unit: "°C", group: 'other' },
  { index: 118, name: 'pump_hysteresis', description: "Histereza włączania pompy (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "°C", group: 'pumps' },
  { index: 119, name: 'water_heater_target_temp', label: "Temperatura zadana CWU", description: "Temperatura wody w zasobniku CWU (instr. 860P str. 12, Pellux str. 16).", rating: "Bezpieczny z aplikacji. Sprawdzony zapis z konsoli.", unit: "°C", group: 'water_heater' },
  { index: 120, name: 'min_water_heater_target_temp', label: "Minimalna temperatura CWU", description: "Najniższa zadana CWU, jaką może ustawić użytkownik (instr. 860P str. 42).", rating: "Ostrożnie. Menu serwisowe. Zmiana potrzebna tylko wtedy, gdy zadana CWU ma zejść poniżej 20 °C.", unit: "°C", group: 'water_heater' },
  { index: 121, name: 'max_water_heater_target_temp', label: "Maksymalna temperatura CWU", description: "Do tej temperatury regulator grzeje CWU, gdy zrzuca nadmiar ciepła z przegrzanego kotła. Za wysoka grozi poparzeniem, za niska odbiera kotłowi zrzut ciepła (instr. 860P str. 42 i 45).", rating: "Nie ruszać. Parametr bezpieczeństwa.", unit: "°C", group: 'water_heater' },
  { index: 122, name: 'water_heater_work_mode', label: "Tryb pracy pompy CWU", description: "Wyłączony (bez ładowania CWU), Priorytet (pompa CO stoi do załadowania CWU), Bez priorytetu (pompy CO i CWU razem) (instr. 860P str. 12, Pellux str. 15). Kolejność 0/1/2 według kopii ustawień (niepotwierdzona).", rating: "Bezpieczny z aplikacji.", group: 'water_heater' },
  { index: 123, name: 'water_heater_hysteresis', label: "Histereza zasobnika CWU", description: "Pompa CWU startuje, gdy CWU spadnie poniżej zadanej minus histereza. Mała histereza daje częstsze ładowanie (instr. 860P str. 12, Pellux str. 16). U nas ładowanie poniżej 50 − 15 = 35 °C.", rating: "Bezpieczny z aplikacji.", unit: "°C", group: 'water_heater' },
  { index: 124, name: 'water_heater_disinfection', label: "Dezynfekcja CWU", description: "Raz w tygodniu, w nocy z niedzieli na poniedziałek o 2:00, regulator grzeje CWU do 70 °C i trzyma 10 min. Ryzyko poparzenia, domowników trzeba uprzedzić (instr. 860P str. 12–13, Pellux str. 15–16).", rating: "Ostrożnie. Ryzyko poparzenia. Nie włączać przy wyłączonej obsłudze CWU.", kind: 'switch', group: 'water_heater' },
  { index: 125, name: 'summer_mode', label: "Tryb LATO (Lato / Zima / Auto)", description: "Lato: kocioł grzeje tylko CWU, ogrzewanie CO jest wyłączone. Auto: przełączanie według czujnika pogodowego. Przy LATO wszystkie odbiorniki mogą być wyłączone, więc trzeba sprawdzić, czy kocioł się nie przegrzeje (instr. 860P str. 12, Pellux str. 11 i 16). Kolejność 0/1/2 według kopii ustawień (niepotwierdzona; u nas 0 przy grzaniu CO, więc 0 to prawdopodobnie Zima).", rating: "Bezpieczny z aplikacji. Nie włączać LATO przy niesprawnej pompie CWU (instr. 850P2 str. 13).", group: 'summer' },
  { index: 126, name: 'summer_mode_enable_temp', label: "Temperatura włączenia trybu LATO", description: "W trybie Auto: temperatura zewnętrzna, powyżej której włącza się LATO (instr. 850P2 str. 13, 860P str. 12).", rating: "Bezpieczny z aplikacji.", unit: "°C", group: 'summer' },
  { index: 127, name: 'summer_mode_disable_temp', label: "Temperatura wyłączenia trybu LATO", description: "W trybie Auto: temperatura zewnętrzna, poniżej której LATO się wyłącza (instr. 850P2 str. 13, 860P str. 12).", rating: "Bezpieczny z aplikacji.", unit: "°C", group: 'summer' },
  { index: 128, name: 'water_heater_work_extension', label: "Wydłużenie pracy CWU", description: "Po załadowaniu CWU pompa CWU pracuje dłużej, żeby schłodzić kocioł. Dotyczy zwłaszcza trybu LATO (instr. 860P str. 42, 850P2 str. 43).", rating: "Ostrożnie. Za mało grozi przegrzaniem kotła latem, za dużo grzaniem CWU bez potrzeby.", unit: "min", group: 'water_heater' },
  { index: 129, name: 'circulation_control', description: "Włączenie obsługi pompy cyrkulacyjnej (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", kind: 'switch', group: 'buffer' },
  { index: 130, name: 'circulation_pause', label: "Czas postoju pompy cyrkulacyjnej", description: "Przerwa między okresami pracy pompy cyrkulacyjnej. Zalecane 15–40 min (instr. 860P str. 42).", rating: "Nie dotyczy.", unit: "min", group: 'buffer' },
  { index: 131, name: 'circulation_work', label: "Czas pracy pompy cyrkulacyjnej", description: "Czas pracy pompy cyrkulacyjnej w cyklu. Instrukcja zaleca 60–120 s, a PyPlumIO podaje minuty (instr. 860P str. 42).", rating: "Nie dotyczy.", unit: "min", group: 'buffer' },
  { index: 132, name: 'circulation_start_temp', label: "Temperatura startu pompy cyrkulacyjnej", description: "Temperatura CWU, przy której rusza pompa cyrkulacyjna (instr. 860P str. 42).", rating: "Nie dotyczy.", unit: "°C", group: 'buffer' },
  { index: 133, name: 'buffer_control', label: "Obsługa bufora", description: "Włącza pracę z buforem (instr. 860P str. 42).", rating: "Nie dotyczy.", kind: 'switch', group: 'buffer' },
  { index: 134, name: 'max_buffer_temp', description: "Maksymalna temperatura bufora (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "°C", group: 'buffer' },
  { index: 135, name: 'min_buffer_temp', description: "Minimalna temperatura bufora (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "°C", group: 'buffer' },
  { index: 136, name: 'buffer_hysteresis', description: "Histereza bufora (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", unit: "°C", group: 'buffer' },
  { index: 137, name: 'buffer_load_start', label: "Temperatura rozpoczęcia ładowania bufora", description: "Poniżej tej temperatury górnej części bufora zaczyna się ładowanie (instr. 860P str. 42).", rating: "Nie dotyczy.", unit: "°C", group: 'buffer' },
  { index: 138, name: 'buffer_load_stop', label: "Temperatura zakończenia ładowania bufora", description: "Ładowanie kończy się, gdy dolna część bufora osiągnie tę temperaturę (instr. 860P str. 42).", rating: "Nie dotyczy.", unit: "°C", group: 'buffer' },
];

export const MIXER_PARAMETERS: EcomaxParameterDefinition[] = [
  { index: 0, name: 'mixer_target_temp', label: "Temperatura zadana mieszacza", description: "Temperatura wody w obiegu mieszacza, np. 50 °C (instr. 860P str. 10 i 13). Pomijana przy sterowaniu pogodowym mieszacza.", rating: "Bezpieczny z aplikacji, ale u nas nic nie zmieni, dopóki nr 4 = 1.", unit: "°C" },
  { index: 1, name: 'min_target_temp', label: "Minimalna temperatura mieszacza", description: "Najniższa zadana mieszacza, także przy obniżeniach i sterowaniu pogodowym (instr. 860P str. 43).", rating: "Ostrożnie. Menu serwisowe.", unit: "°C" },
  { index: 2, name: 'max_target_temp', label: "Maksymalna temperatura mieszacza", description: "Najwyższa zadana mieszacza, także z krzywej. Przy obsłudze „Włączona podłoga” wyłącza pompę, gdy obieg przekroczy max + 5 °C; dla podłogi nie więcej niż 45–50 °C (instr. 860P str. 43).", rating: "Ostrożnie. Menu serwisowe. Dla grzejników nie chroni przed niczym, dla podłogi to ochrona.", unit: "°C" },
  { index: 3, name: 'thermostat_decrease_target_temp', label: "Termostat pokojowy mieszacza (obniżenie temp. zadanej mieszacza)", description: "O ile spada zadana mieszacza po zadziałaniu termostatu pokojowego. Dobór doświadczalny, np. 5 °C bez czujnika pogodowego, 2 °C z czujnikiem (instr. 860P str. 13).", rating: "Bezpieczny z aplikacji.", unit: "°C" },
  { index: 4, name: 'weather_control', label: "Sterowanie pogodowe mieszacza", description: "Zadana mieszacza liczona z temperatury zewnętrznej według krzywej (instr. 860P str. 13–14).", rating: "Ostrożnie. Wyłączenie przełącza mieszacz na stałą zadaną.", kind: 'switch' },
  { index: 5, name: 'heating_curve', label: "Krzywa grzewcza mieszacza", description: "Nachylenie krzywej. Podłoga 0,2–0,6, grzejniki 1,0–1,6 (instr. 860P str. 14).", rating: "Bezpieczny z aplikacji. Zmieniać małymi krokami, co kilka dni.", step: 0.1 },
  { index: 6, name: 'heating_curve_shift', label: "Przesunięcie równoległe krzywej", description: "Przesuwa krzywą. Temperatura pokojowa = 20 °C + przesunięcie, np. +2 °C daje ok. 22 °C (instr. 860P str. 13).", rating: "Bezpieczny z aplikacji. Najprostsza „cieplej/chłodniej” dla grzejników.", unit: "°C", offset: 20 },
  { index: 7, name: 'weather_factor', label: "Współczynnik temperatury pokojowej", description: "Korekta zadanej mieszacza od panelu pokojowego: (zadana pokojowa − zmierzona) × współczynnik / 10. 0 = bez korekty. Za duży daje wahania (instr. 860P str. 13–14).", rating: "Bezpieczny z aplikacji." },
  { index: 8, name: 'work_mode', label: "Obsługa mieszacza", description: "Wyłączona / Włączona CO (grzejniki; mieszacz otwiera się w pełni przy przegrzaniu kotła) / Włączona podłoga (ograniczenie do max) / Tylko pompa (instr. 860P str. 43). Kolejność 0–3 według kopii ustawień.", rating: "Nie ruszać. Zależy od instalacji; zła wartość może przegrzać podłogę albo wyłączyć obieg." },
  { index: 9, name: 'mixer_input_dead_zone', label: "Nieczułość mieszacza", description: "Martwa strefa: siłownik rusza, gdy temperatura obiegu różni się od zadanej o więcej niż ta wartość. Oszczędza siłownik (instr. 860P str. 43).", rating: "Tylko serwis.", unit: "°C", step: 0.1 },
  { index: 10, name: 'thermostat_operation', description: "Działanie termostatu mieszacza (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", kind: 'switch' },
  { index: 11, name: 'thermostat_mode', label: "Wybór termostatu (mieszacza)", description: "Wyłączony / Uniwersalny / ecoSTER T1–T3 (instr. 860P str. 43, Pellux str. 46).", rating: "Ostrożnie." },
  { index: 12, name: 'disable_pump_on_thermostat', label: "Wyłączenie pompy od termostatu", description: "TAK: po rozwarciu styku termostatu zamyka mieszacz i wyłącza jego pompę. Instrukcja tego nie zaleca, pokój może się wychłodzić (instr. 860P str. 43).", rating: "Ostrożnie.", kind: 'switch' },
  { index: 13, name: 'summer_work', description: "Praca mieszacza w trybie LATO (opis z nazwy, niepotwierdzony).", rating: "Nie dotyczy.", kind: 'switch' },
];
